"""
Security Fix Data Model
Represents a remediation solution generated by the Blue Team engine.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional


# ── Constants ─────────────────────────────────────────────────────────────────

FIX_TYPES = ["automated", "semi_automated", "manual"]

FIX_STRATEGIES = [
    "template_replacement",
    "value_encryption",
    "configuration_change",
    "removal",
    "manual_guidance",
]

PRIORITY_LEVELS = ["immediate", "high", "medium", "low"]

EFFORT_LEVELS = ["low", "medium", "high"]

VALIDATION_STATUSES = ["pending", "validated", "failed"]


# ── Security Fix ───────────────────────────────────────────────────────────────

@dataclass
class SecurityFix:
    """
    Represents a remediation solution for a detected security issue.

    Generated by the Blue Team engine using predefined templates.
    Fixes are deterministic — no AI involvement in generation.
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    fix_id: str                     # e.g. "FIX-20260101-abc123"
    issue_id: str                   # links back to SecurityIssue
    issue_title: str

    # ── Fix Type ──────────────────────────────────────────────────────────────
    fix_type: str                   # automated | semi_automated | manual
    template_id: Optional[str]      # e.g. "CRED-FIX-001"

    # ── Fix Content ───────────────────────────────────────────────────────────
    original_code: str              # the vulnerable code snippet
    fixed_code: str                 # the replacement code
    explanation: str                # human-readable explanation

    # ── Fix Strategy ──────────────────────────────────────────────────────────
    strategy: str                   # template_replacement | value_encryption | etc.

    # ── Metadata ──────────────────────────────────────────────────────────────
    priority: str = "medium"        # immediate | high | medium | low
    effort: str = "medium"          # low | medium | high
    risk_reduction: float = 0.0     # estimated risk reduction percentage (0-100)

    # ── Validation ────────────────────────────────────────────────────────────
    validation_status: str = "pending"      # pending | validated | failed
    validation_errors: List[str] = field(default_factory=list)

    # ── Application Status ────────────────────────────────────────────────────
    applied: bool = False
    applied_at: Optional[datetime] = None

    # ── Side Effects ──────────────────────────────────────────────────────────
    side_effects: List[str] = field(default_factory=list)
    breaking_change: bool = False

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate fields after initialization."""
        assert self.fix_type in FIX_TYPES, \
            f"Invalid fix_type: {self.fix_type}"
        assert self.strategy in FIX_STRATEGIES, \
            f"Invalid strategy: {self.strategy}"
        assert self.priority in PRIORITY_LEVELS, \
            f"Invalid priority: {self.priority}"
        assert self.effort in EFFORT_LEVELS, \
            f"Invalid effort: {self.effort}"
        assert self.validation_status in VALIDATION_STATUSES, \
            f"Invalid validation_status: {self.validation_status}"

    @property
    def is_auto_fixable(self) -> bool:
        """Return True if this fix can be applied automatically."""
        return (
            self.fix_type == "automated" and
            self.validation_status == "validated" and
            not self.breaking_change
        )

    @property
    def has_side_effects(self) -> bool:
        """Return True if this fix has known side effects."""
        return len(self.side_effects) > 0

    def mark_applied(self):
        """Mark this fix as applied."""
        self.applied = True
        self.applied_at = datetime.now()

    def mark_validated(self):
        """Mark validation as successful."""
        self.validation_status = "validated"
        self.validation_errors = []

    def mark_validation_failed(self, errors: List[str]):
        """Mark validation as failed with error details."""
        self.validation_status = "failed"
        self.validation_errors = errors

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary for reporting and export."""
        return {
            "fix_id": self.fix_id,
            "issue_id": self.issue_id,
            "issue_title": self.issue_title,
            "fix_type": self.fix_type,
            "template_id": self.template_id,
            "strategy": self.strategy,
            "priority": self.priority,
            "effort": self.effort,
            "risk_reduction": self.risk_reduction,
            "validation_status": self.validation_status,
            "validation_errors": self.validation_errors,
            "applied": self.applied,
            "applied_at": self.applied_at.isoformat() if self.applied_at else None,
            "side_effects": self.side_effects,
            "breaking_change": self.breaking_change,
            "original_code": self.original_code,
            "fixed_code": self.fixed_code,
            "explanation": self.explanation,
        }

    def __repr__(self) -> str:
        return (
            f"SecurityFix(id={self.fix_id!r}, "
            f"type={self.fix_type!r}, "
            f"strategy={self.strategy!r}, "
            f"applied={self.applied})"
        )
